"""empty message

Revision ID: 490c4cf559be
Revises: ed1675b3c616
Create Date: 2024-05-20 10:59:32.981107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490c4cf559be'
down_revision = 'ed1675b3c616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mad_lib',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story', sa.String(length=1000), nullable=False),
    sa.Column('questions', sa.String(length=1000), nullable=False),
    sa.Column('placeholders', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Madlib')
    op.drop_table('Placeholder')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Placeholder',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('madlib_id', sa.INTEGER(), nullable=True),
    sa.Column('value', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['madlib_id'], ['Madlib.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Madlib',
    sa.Column('content', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('content')
    )
    op.drop_table('mad_lib')
    # ### end Alembic commands ###
