"""empty message

Revision ID: c26b00840856
Revises: 1a0107c99a3c
Create Date: 2024-05-13 15:00:16.243882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c26b00840856'
down_revision = '1a0107c99a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Madlib',
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('content')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Madlib')
    # ### end Alembic commands ###
